---
title: "Data Manipulation"
output: html_document
---

This document will show how to *manipulate* data. 


## Import and clean
```{r}
litters_df = read_csv("data_import_examples/FAS_litters.csv", 
                      na=c("NA", "", "."))
litters_df = janitor::clean_names(litters_df)

pups_df = read_csv("data_import_examples/FAS_pups.csv", 
                      na=c("NA", "", "."))
pups_df = janitor::clean_names(pups_df)
```

## `select`
Use `select` to select variables
```{r}
select(litters_df, group, litter_number, gd0_weight) 
# returns the 3 selected columns and all the rows in it
select(litters_df, group:gd18_weight)
# returns first 4 columns and all the rows in it
select(litters_df, -pups_survive)
# returns all but the last column because we removed it
```


```{r}
relocate(litters_df, gd0_weight, gd18_weight)
```


```{r}
select(pups_df,1:3 )
```
## `filter`
```{r}
drop_na(litters_df)
drop_na(litters_df, gd0_weight)
male_pups = pups_df %>% filter(sex==1)
```
```{r}
mutate(litters_df, wt_gain = gd18_weight-gd0_weight)
```







